from logging.config import stopListening
import re
from time import sleep
from time import time, sleep
from turtle import position
import long_responses as long
from pynput.mouse import Button, Controller
from pynput.keyboard import Key, Controller as KeyControl

keyboard = KeyControl()
mouse = Controller()

while True:
    sleep(10)
    keyboard.press(Key.alt.value)
    keyboard.press(Key.tab.value)
    keyboard.release(Key.tab.value)
    keyboard.release(Key.alt.value)
    sleep(1)
    mouse.position = (384, 800)
    mouse.press(Button.left)
    mouse.position = (1538, 800)
    mouse.release(Button.left)
    sleep(1)
    keyboard.press(Key.ctrl.value)
    keyboard.press("c")
    keyboard.release(Key.ctrl.value)
    keyboard.release("c")
    sleep(1)
    keyboard.press(Key.alt.value)
    keyboard.press(Key.tab.value)
    keyboard.release(Key.tab.value)
    keyboard.release(Key.alt.value)
    sleep(1)
    mouse.position = (343, 867)
    mouse.press(Button.left)
    mouse.release(Button.left)
    sleep(2)
    keyboard.press(Key.ctrl.value)
    keyboard.press(Key.shift.value)                                                                                                                         
    keyboard.press("v")
    keyboard.release(Key.ctrl.value)
    keyboard.release(Key.shift.value)
    keyboard.release("v")
    sleep(1)
    keyboard.press(Key.enter.value)
    keyboard.release(Key.enter.value)
    sleep(1)
    mouse.position = (312, 852)
    mouse.press(Button.left)
    mouse.position = (940, 852)
    mouse.release(Button.left)
    sleep(1)
    keyboard.press(Key.ctrl.value)
    keyboard.press(Key.shift.value)                                                                                                                         
    keyboard.press("c")
    keyboard.release(Key.ctrl.value)
    keyboard.release(Key.shift.value)
    keyboard.release("c")
    sleep(1)
    keyboard.press(Key.alt.value)
    keyboard.press(Key.tab.value)
    keyboard.release(Key.tab.value)
    keyboard.release(Key.alt.value)
    sleep(1)
    mouse.position = (397, 855)
    mouse.press(Button.left)
    mouse.release(Button.left)
    sleep(1)
    keyboard.press(Key.ctrl.value)
    keyboard.press("v")
    keyboard.release(Key.ctrl.value)
    keyboard.release("v")
    sleep(1)
    keyboard.press(Key.enter.value)
    keyboard.release(Key.enter.value)
    sleep(1)
    keyboard.press(Key.alt.value)
    keyboard.press(Key.tab.value)
    keyboard.release(Key.tab.value)
    keyboard.release(Key.alt.value)
    sleep(5)